steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/jacks-project-398813/docker-repo/docker-image:tag1 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/jacks-project-398813/docker-repo/docker-image:tag1'
